import type { NextPage } from 'next'
import Head from 'next/head';
import React from 'react';
import HeadNav from '../components/HeadNav/HeadNav';
import PrimaryLayout from '../components/Layouts/PrimaryLayout/PrimaryLayout';
import MainContent from '../components/MainContent/MainContent';
import SideNav from '../components/SideNav/SideNav';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Just Simple Next App</title>
        <meta name="description" content="Generated by create next app with simple react design" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <React.Fragment>
        <PrimaryLayout>
          <div className={styles.nav_parent}>
            <div className={styles.side_nav}>
              <SideNav/>
            </div>
            <div className={styles.container + " " + styles.main_bg}>
              <div className={styles.head_nav}>
                <HeadNav/>
              </div>
              <MainContent />
            </div>
          </div>
        </PrimaryLayout>
      </React.Fragment>
      
    </React.Fragment>
  )
}

export default Home
